services:
  - type: web
    name: reservee-frontend
    env: static
    buildCommand: npm run build:render
    staticPublishPath: ./dist
    headers:
      - path: "*.css"
        name: "Content-Type"
        value: "text/css"
      - path: "*.js"
        name: "Content-Type"
        value: "application/javascript"
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
